name: Deploy Container image to aws ECR
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs: 
    aws_ecr_dockerfile_deploy:
        runs-on: ubuntu-latest
        name: AWS ecr deploy- A job that deployys a image container using a aws_ecr_dockerfile_deploy
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Deploy container image to AWS ECR
              uses: Timur-IT/aws-ecr-deploy@v0.08
              id: deploy 
              with:
                access_key_id: ${{ secrets.MY_AWS_ACCESS_KEY }}
                secret_access_key: ${{ secrets.MY_AWS_SECRET_KEY }}
                image_name: nginx
                repo_uri: 822137640983.dkr.ecr.us-west-1.amazonaws.com/app-main:nginx

            - name: Get the output status
              run: echo "${{ steps.deploy.outputs.status }}"
