name: Create Amazon EKS on AWSFargate


on: 
  push:
    branches: 
      - master

jobs:
  create_cluster:
    runs-on: ubuntu-latest
    name: Create an EKS on Fargate cluster
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region: us-west-1
    - name: Provision cluster
      uses: aws-actions/amazon-eks-fargate@v0.1
